---
title: 'Lab 1 Question 3: Are survey respondents who have had someone in their home infected by COVID-19 more likely to disapprove of the way their governor is handling the pandemic?'
author: "Yao Chen, Jenny Conde, Satheesh Joseph, Paco Valdez, Yi Zhang"
output: 
  bookdown::pdf_document2: 
    toc: true
---

```{r load packages, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
# library(tidyverse) # if you want more, but still core, toolkit
library(haven)

library(tidyverse) 
library(magrittr)
library(knitr)
library(patchwork)
theme_set(theme_bw())
options(tinytex.verbose = TRUE)
```

```{r load and clean data, echo=FALSE, warning=TRUE, message=FALSE}
# Load data
df <- read_dta('data/anes_timeseries_2020_stata_20210211.dta')

# Useful variables
# V201145 -- PRE: APPROVE OR DISAPPROVE R’S GOVERNOR HANDLING COVID-19
  # 1 = approve, 2 = disapprove
gov_approve = 1
gov_disapprove = 2
# V201624 -- PRE: ANYONE IN HOUSEHOLD TESTED POS FOR COVID-19
  # 1 = someone tested positive, 2 = no one tested positive 
pos_test = 1
no_pos_test = 2
# Less useful but still interesting
# V201146 -- PRE: HOW MUCH APPROVE/DISAPPROVE R’S GOVERNOR HANDLING COVID-19
# V201625 -- PRE: ANYONE IN HOUSEHOLD COVID-19 BASED ON SYMPTOMS

df_small <- data.frame(gov=df$V201145, covid=df$V201624)

df_clean <- df_small
df_clean <- df_clean[df_clean$covid > 0,] # remove interview breakoff/refused
df_clean <- df_clean[df_clean$gov > 0,] # remove don't know/refused

```


## Importance and Context
<!-- You can (and should delete each of these comments lines in your final report) --> 
<!-- Explain why the reader should care about your research question. -->

## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What are some basic features of the data distribution? --> 
<!-- What changes do you make to the data and why? --> 

- `V201145`: `APPROVE OR DISAPPROVE R’S GOVERNOR HANDLING COVID-19`

- `V201624`: `ANYONE IN HOUSEHOLD TESTED POS FOR COVID-19`

```{r}
summary(df_clean)
```


```{r, echo = FALSE, fig.cap='Voters\' Approval of Governor and Household COVID-19 Tests', fig.pos='!h'}
df_clean_mod <- mutate(df_clean, gov_approval = ifelse(gov == gov_approve, "Approve", "Disapprove"))
df_clean_mod <- mutate(df_clean_mod, positive_test = ifelse(covid == pos_test, "Positive Test", "No Positive Test"))

gov_count <- df_clean_mod %>%
  group_by(gov_approval) %>%
  summarize(count=n())

pos_test_count <- df_clean_mod %>%
  group_by(positive_test) %>%
  summarize(count = n())

gov_pie_chart <- gov_count %>%
  ggplot() +
  aes(x = "", y = count, fill = gov_approval) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(fill = "Approve or Disapprove of \nGovernor's Response",
       title = "Distribution of Approval of\nGovernor's COVID-19 Handling") +
  theme_void()

covid_pie_chart <- pos_test_count %>%
  ggplot() +
  aes(x = "", y = count, fill = positive_test) + 
  geom_bar(stat = "identity", width = 1) + 
  coord_polar("y", start = 0) +
  labs(fill = "COVID-19 Case in Household",
       title = "Distribution of Households\nwith Positive COVID-19 Tests") +
  theme_void()

(gov_pie_chart) | (covid_pie_chart)
```


```{r, echo = FALSE, fig.pos = '!h'}
summary_table <- prop.table(table(df_clean_mod %>% select(3, 4)))
kable(summary_table,
      digits = 3,
      caption = "Cross Tab of Governor Approval and Positive COVID-19 Tests",
      booktabs = TRUE)
```


# PACO START HERE PLEASE

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance? --> 