---
title: 'Lab 1: Question 2'
author: "Yao Chen, Jenny Conde, Satheesh Joseph, Paco Valdez, Yi Zhang"
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2) 
# library(tidyverse) # if you want more, but still core, toolkit
```

```{r load and clean data, echo=FALSE, warning=TRUE, message=FALSE}
# Load data
df <- read_dta('data/anes_timeseries_2020_stata_20210211.dta')

# Useful variables
# V201018 -- PRE: PARTY OF REGISTRATION
# V201151 -- PRE: FEELING THERMOMETER: JOE BIDEN, DEMOCRATIC PRESIDENTIAL CANDIDATE
# V201153 -- PRE: FEELING THERMOMETER: KAMALA HARRIS, DEMOCRATIC VICE-PRESIDENTIAL CANDIDATE
dem_df <- data.frame(party=df$V201018, Biden=df$V201151, Harris = df$V201153) %>% filter(party == 1)

cat(" Biden : Mean - ", mean(dem_df[["Biden"]]), " sd - ", sd(dem_df[["Biden"]]), "\n")
cat(" Harris : Mean - ", mean(dem_df[["Harris"]]), " sd - ", sd(dem_df[["Harris"]]), "\n")
```

## Importance and Context
<!-- You can (and should delete each of these comments lines in your final report) --> 
<!-- Explain why the reader should care about your research question. -->

## Description of Data
<!-- Explain how your research question is operationalized, including whether the variables you create are appropriate to study the concepts in question. --> 
<!-- What are some basic features of the data distribution? --> 
<!-- What changes do you make to the data and why? --> 

## Most appropriate test 
<!-- Explain which test is the most appropriate to answer your question and why it is the most appropriate --> 
<!-- List every assumption that your test requires and evaluate it. -->

## Test, results and interpretation
<!-- What are the results of your test? --> 
<!-- What do the results of this test mean? What is the practical significance? --> 